apiVersion: v1
kind: ConfigMap
metadata:
  name: headplane
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "headplane.labels" . | nindent 4 }}
data:
  config.yaml: |
    server:
      host: 0.0.0.0
      port: 3000
      cookie_secret_path: /var/secrets/headplane/server/{{ .Values.headplane.config.cookieSecret.secretKey }}
      cookie_secure: true
    headscale:
      public_url: {{ default .Values.headscale.config.url .Values.headplane.config.headscale.public_url }}
      {{- if .Values.headscale.enabled }}
      url: http://127.0.0.1:8080
      {{- else }}
      config_path: /etc/headscale/config.yaml
      config_strict: false
      url: {{ .Values.headplane.config.headscale.url }}
      {{- end }}
      # api_key: ""
      api_key_path: /var/secrets/headplane/headscale/{{ .Values.headplane.config.headscale.apiKey.secretKey }}
    integration:
      kubernetes:
        enabled: true
        validate_manifest: true
        pod_name: replaced-by-environment-variable
    {{- if .Values.headplane.config.oidc.enabled }}
    oidc:
      issuer: {{ .Values.headplane.config.oidc.issuerUrl }}
      client_id: {{ .Values.headplane.config.oidc.clientId }}
      client_secret_path: /var/secrets/headplane/oidc/{{ .Values.headplane.config.oidc.clientSecret.secretKey }}
      disable_api_key_login: {{ .Values.headplane.config.oidc.disableApiKeyLogin }}
      token_endpoint_auth_method: {{ .Values.headplane.config.oidc.tokenEndpointAuthMethod }}
      redirect_uri: {{ .Values.headplane.config.url }}/admin/oidc/callback
    {{- end }}
