{{ if not .Values.headplane.config.cookieSecret.secretName }}
---
apiVersion: v1
kind: Secret
metadata:
  name: headplane-cookie-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "headplane.labels" . | nindent 4 }}
stringData:
  cookie-secret: {{ include "headplane.cookieSecret" . }}
{{- end }}
{{- if and .Values.headplane.config.oidc.enabled }}
{{- if not .Values.headplane.config.oidc.clientSecret.secretName }}
---
apiVersion: v1
kind: Secret
metadata:
  name: headplane-oidc-client-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "headplane.labels" . | nindent 4 }}
stringData:
  client-secret: {{ required "headplane plaintext client secret value required" .Values.headplane.config.oidc.clientSecret.value }}
{{- end }}
{{- end }}
