---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "headplane.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "headplane.labels" . | nindent 4 }}
spec:
  ports:
  - name: headplane-ui
    port: 80
    protocol: TCP
    targetPort: app
  selector:
    {{- include "headplane.selectorLabels" . | nindent 4 }}
  type: ClusterIP
